// import '../../node_modules/jquery/dist/jquery.min.js'
import '../../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'
import '../../node_modules/summernote/dist/summernote-bs4.js'
import '../../node_modules/chocolat/dist/js/jquery.chocolat.min.js'
import '../../public/assets/js/stisla.js'
import '../../public/assets/js/custom.js'
import '../../public/assets/js/page/jquery.nicescroll.min'
